#!/usr/bin/env python3
# Copyright 2020 Sebastian Wiesner <sebastian@swsnr.de>
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License. You may obtain a copy of
# the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations under
# the License.

import sys
import json
from locale import LC_ALL, setlocale
from datetime import date
from gi.repository import GLib


def print_date():
    today = date.today()
    output = {
        'full_text': today.strftime('📅 %A, %Y-%m-%d (KW %V)'),
        'short_text': today.strftime('📅 %m-%d (37)')
    }
    json.dump(output, sys.stdout, ensure_ascii=False, indent=None)
    sys.stdout.write('\n')
    sys.stdout.flush()


def main():
    setlocale(LC_ALL, '')
    print_date()
    # TODO: Refresh when screen is unlocked
    GLib.MainLoop().run()


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        pass
