#!/usr/bin/env python3
# Copyright 2019 Sebastian Wiesner <sebastian@swsnr.de>
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License. You may obtain a copy of
# the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations under
# the License.

import sys
import json
from textwrap import shorten
from subprocess import Popen, PIPE, run


def update_window_title():
    title = run(['xdotool', 'getactivewindow', 'getwindowname'],
                capture_output=True, text=True)
    if title.returncode == 0:
        print(shorten(title.stdout, width=200, placeholder='…'))
    else:
        print("<no active window>")
    sys.stdout.flush()


def main():
    update_window_title()
    events = ['window', 'workspace']
    process = Popen(['i3-msg', '-t', 'subscribe', '-m', json.dumps(events)],
                    bufsize=1, stdout=PIPE, universal_newlines=True)
    for line in process.stdout:
        data = json.loads(line)
        if data['change'] in {'focus', 'title'}:
            update_window_title()


if __name__ == '__main__':
    main()
