#!/usr/bin/env python3
# Copyright 2019 Sebastian Wiesner <sebastian@swsnr.de>
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License. You may obtain a copy of
# the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations under
# the License.

import random
from urllib.request import urlopen

from lxml import etree, html


def extract_quotes(item):
    description = html.fromstring(item.findtext('description'))
    # Split by marker and drop last element which is the "More…" link.
    return [s.strip()
            for s in description.text_content().split('+++')[:-1]
            if s]


def main():
    with urlopen('http://feeds.feedburner.com/blogspot/rkEL') as source:
        feed = etree.parse(source)
    newstickers = feed.findall('.//item[category = "Newsticker"]')
    quotes = [quote for item in newstickers for quote in extract_quotes(item)]
    print('📯 {}'.format(random.choice(quotes)))


if __name__ == '__main__':
    main()
