#!/usr/bin/env python3
# Copyright 2020 Sebastian Wiesner <sebastian@swsnr.de>
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License. You may obtain a copy of
# the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations under
# the License.


import sys
import time
from locale import LC_ALL, setlocale
from datetime import datetime


def print_time():
    sys.stdout.write(datetime.today().strftime('🕰️ %H:%M'))
    sys.stdout.write('\n')
    sys.stdout.flush()


def main():
    setlocale(LC_ALL, '')
    print_time()
    while True:
        time.sleep(60)
        print_time()


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        pass
