#!/bin/bash
# Copyright 2019 Sebastian Wiesner <sebastian@swsnr.de>
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License. You may obtain a copy of
# the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations under
# the License.

set -e

config_home="${XDG_CONFIG_HOME:-$HOME/.config}"
location="$(< "${config_home}"/i3blocks/location)"

if [[ "$BLOCK_BUTTON" -eq 1 ]]; then
  xdg-open "https://wttr.in/${location}" &> /dev/null &
fi

exec curl -s "https://wttr.in/${location}?format=%c%t"
