#!/usr/bin/bash
# Copyright Sebastian Wiesner <sebastian@swsnr.de>
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License. You may obtain a copy of
# the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations under
# the License.

set -euo pipefail

echo "=== shfmt"
shfmt -i 4 -l -d **/*.bash bin/ui-theme bin/game-mode-hook bin/toggle-nightlight
echo "=== shellcheck"
shellcheck **/*.bash bin/ui-theme bin/game-mode-hook bin/toggle-nightlight
echo "=== fish_indent"
fish_indent -c fish/**/*.fish
echo "=== ruff"
ruff check .
