# Unfortunately helix does not yet switch themes automatically for light/dark mode, see
# https://github.com/helix-editor/helix/issues/2158, so we use a custom symlink
# to switch the active theme.
#
# See update-theme fish function and install.bash for how we manage this
# symlink.
theme = "swsnr-light-dark"

[editor]
# Highlight lines with cursors
cursorline = true
# Automatically save when focus moves away from the terminal window
auto-save = true
# Force true color and undercurls; all relevant terminals support these, even gnome-terminal does.
true-color = true
undercurl = true
# Mark common line widths
rulers = [80, 120]
# Show open buffers
bufferline = "multiple"

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.indent-guides]
# Render indent guides
render = true

[editor.soft-wrap]
# Soft-wrap long lines at text width
enable = true
wrap-at-text-width = true

[keys.normal]
"A-q" = ":reflow"

[keys.insert]
j = { k = "normal_mode" }