" Copyright Sebastian Wiesner <sebastian@swsnr.de>
"
" Licensed under the Apache License, Version 2.0 (the "License"); you may not
" use this file except in compliance with the License. You may obtain a copy of
" the License at
"
"     http://www.apache.org/licenses/LICENSE-2.0
"
" Unless required by applicable law or agreed to in writing, software
" distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
" WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
" License for the specific language governing permissions and limitations under
" the License.

" Simple vim configuration to make old vim behave sensibly, for old systems
set nocompatible

syntax on " Enable syntax highlight
filetype plugin indent on " Enable filetype detection

set autoindent
set autoread
set backspace=indent,eol,start
set complete-=i
set display=lastline
set encoding=utf-8
set hlsearch
set incsearch
set laststatus=2
set mouse=a
set smarttab
set ttyfast
set viminfo+=!
set wildmenu
set ttymouse=xterm2

" Some reasonable defaults to make vim more bearable
set number
set relativenumber
set cursorline
set shortmess+=atOIc
set smartcase
set ignorecase
set textwidth=80
set shiftwidth=4
set expandtab
set scrolloff=8
set sidescrolloff=8
set splitright
set splitbelow
set foldmethod=indent
set foldlevelstart=10
set hidden
set showmatch
set completeopt=menuone

" escape sucks
inoremap jk <ESC>
