#!/bin/bash
# Copyright 2020 Sebastian Wiesner <sebastian@swsnr.de>
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License. You may obtain a copy of
# the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations under
# the License.

config_dir="${XDG_CONFIG_HOME:-$HOME/.config}/i3blocks/"
enabled="${config_dir}/home-enabled"
hidden="${config_dir}/home-hidden"

# If the block's hidden don't do anything at all
if [[ -f "$hidden" ]]; then
    exit
fi

# Enable/disable with right click
if [[ -n "$BLOCK_BUTTON" ]]; then
    if [[ -f "${enabled}" ]]; then
        rm -f "${enabled}"
    else
        touch "${enabled}"
    fi
fi

if [[ -f "${enabled}" ]]; then
    exec home -n1
else
    echo '🚆'
fi
