#!/bin/bash
# Copyright 2019 Sebastian Wiesner <sebastian@swsnr.de>
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License. You may obtain a copy of
# the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations under
# the License.

set -e

location_file="${XDG_CONFIG_HOME:-$HOME/.config}/i3blocks/weather-location"

if [[ -f "$location_file" ]]; then
  location="$(<"$location_file")"
else
  location=''
fi

case "$BLOCK_BUTTON" in
1)
  if [[ -n "$location" ]]; then
    xdg-open "https://wttr.in/${location}" &>/dev/null &
  fi
  ;;
3)
  if [[ -n "$location" ]]; then
    new_location="$(echo "$location" | rofi -dmenu -m -4 -p 'Weather location' -mesg 'Pick current location for weather information or enter a new one' || true)"
  else
    new_location="$(rofi -dmenu -m -4 -p 'Weather location' -mesg 'Enter location for weather information' || true)"
  fi

  if [[ -n "$new_location" ]]; then
    echo "$new_location" >"$location_file"
    location="$new_location"
  fi
  ;;
esac

# Append a newline to flush output
if [[ -n "$location" ]]; then
  curl -s "https://wttr.in/${location}?format=%c%t" && echo
else
  echo '<Right-click to set weather location>'
fi
