#!/bin/sh

updates="$(checkupdates)"

if [ -n "${updates}" ]; then
    notify-send --urgency low --expire-time 5000 \
        --app-name 'checkupdates' --icon 'system-software-update' \
        "Updates available:

${updates}"
fi
