#!/bin/bash
# Copyright Sebastian Wiesner <sebastian@swsnr.de>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -euo pipefail
# Inherit set -e down to command substitutions
shopt -s inherit_errexit

extract_kernel_version() {
    local heads
    heads="${1%/vmlinuz}"
    echo "${heads##*/}"
}

main() {
    local kernel_images
    local rebuild_all
    local line

    kernel_images=()

    while read -r line; do
        case "${line}" in
        usr/lib/modules/*/vmlinuz)
            kernel_images+=("/${line}")
            ;;
        *)
            kernel_images+=(/usr/lib/modules/*/vmlinuz)
            break
            ;;
        esac
    done

    for kernel_image in "${kernel_images[@]}"; do
        echo +kernel-install "$@" "$(extract_kernel_version "$kernel_image")" "$kernel_image"
        kernel-install "$@" "$(extract_kernel_version "$kernel_image")" "$kernel_image"
    done
}

main "$@"
