#!/bin/sh

case "${XDG_CURRENT_DESKTOP}" in
    XFCE | *GNOME | i3)
        # Configure QT explicitly on Gnome and XFCE
        export QT_QPA_PLATFORMTHEME=qt5ct;
        ;;
esac

export "$(fish -l -c env | grep -e '^PATH=')"
export "$(fish -l -c env | grep -e '^MANPATH=')"
export "$(fish -l -c env | grep -e '^INFOPATH=')"
