name: "Test"
on: push
jobs:
  check-scripts:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: shellcheck --version
      - run: shellcheck -S info **/*.bash bin/ui-theme
