name: "Test"
on: push
jobs:
  check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      # Check shell scripts
      - run: 'shellcheck --version'
      - run: 'shellcheck **/*.bash bin/ui-theme bin/game-mode-hook'
      - run: |
          curl -fsSL -o ./shfmt https://github.com/mvdan/sh/releases/download/v3.6.0/shfmt_v3.6.0_linux_amd64
          chmod 700 ./shfmt
      - run: ./shfmt --version
      - run: ./shfmt -i 4 -l -d **/*.bash bin/ui-theme bin/game-mode-hook
      # Check fish things
      - run: 'sudo apt-add-repository ppa:fish-shell/release-3'
      - run: 'sudo apt-get update -y'
      - run: 'sudo apt-get install -y fish'
      - run: 'fish --version'
      - run: 'fish_indent -c fish/conf.d/*.fish fish/functions/*.fish fish/config.fish'
      # Check lua code in neovim config
      - uses: JohnnyMorganz/stylua-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --check .
      # Check all python code
      - uses: chartboost/ruff-action@v1
